// A small starter set of major cities used for pre-rendered prayer-times pages.
// Grows via scripts/fetch-cities.ts later. Keep this list ASCII-safe slugs.

export type City = {
  slug: string;
  name: string;
  country: string;
  countryCode: string;
  lat: number;
  lon: number;
  tz: string;
  population: number;
};

export const CITIES: ReadonlyArray<City> = [
  {
    slug: "london",
    name: "London",
    country: "United Kingdom",
    countryCode: "GB",
    lat: 51.5074,
    lon: -0.1278,
    tz: "Europe/London",
    population: 8908081,
  },
  {
    slug: "new-york",
    name: "New York",
    country: "United States",
    countryCode: "US",
    lat: 40.7128,
    lon: -74.006,
    tz: "America/New_York",
    population: 8804190,
  },
  {
    slug: "toronto",
    name: "Toronto",
    country: "Canada",
    countryCode: "CA",
    lat: 43.65107,
    lon: -79.347015,
    tz: "America/Toronto",
    population: 2794356,
  },
  {
    slug: "chicago",
    name: "Chicago",
    country: "United States",
    countryCode: "US",
    lat: 41.8781,
    lon: -87.6298,
    tz: "America/Chicago",
    population: 2716000,
  },
  {
    slug: "los-angeles",
    name: "Los Angeles",
    country: "United States",
    countryCode: "US",
    lat: 34.0522,
    lon: -118.2437,
    tz: "America/Los_Angeles",
    population: 3970000,
  },
  {
    slug: "houston",
    name: "Houston",
    country: "United States",
    countryCode: "US",
    lat: 29.7604,
    lon: -95.3698,
    tz: "America/Chicago",
    population: 2325502,
  },
  {
    slug: "dallas",
    name: "Dallas",
    country: "United States",
    countryCode: "US",
    lat: 32.7767,
    lon: -96.797,
    tz: "America/Chicago",
    population: 1345047,
  },
  {
    slug: "birmingham-uk",
    name: "Birmingham",
    country: "United Kingdom",
    countryCode: "GB",
    lat: 52.4862,
    lon: -1.8904,
    tz: "Europe/London",
    population: 1141816,
  },
  {
    slug: "manchester",
    name: "Manchester",
    country: "United Kingdom",
    countryCode: "GB",
    lat: 53.4808,
    lon: -2.2426,
    tz: "Europe/London",
    population: 553230,
  },
  {
    slug: "paris",
    name: "Paris",
    country: "France",
    countryCode: "FR",
    lat: 48.8566,
    lon: 2.3522,
    tz: "Europe/Paris",
    population: 2148000,
  },
  {
    slug: "berlin",
    name: "Berlin",
    country: "Germany",
    countryCode: "DE",
    lat: 52.52,
    lon: 13.405,
    tz: "Europe/Berlin",
    population: 3769000,
  },
  {
    slug: "amsterdam",
    name: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    lat: 52.3676,
    lon: 4.9041,
    tz: "Europe/Amsterdam",
    population: 872680,
  },
  {
    slug: "brussels",
    name: "Brussels",
    country: "Belgium",
    countryCode: "BE",
    lat: 50.8503,
    lon: 4.3517,
    tz: "Europe/Brussels",
    population: 1211035,
  },
  {
    slug: "stockholm",
    name: "Stockholm",
    country: "Sweden",
    countryCode: "SE",
    lat: 59.3293,
    lon: 18.0686,
    tz: "Europe/Stockholm",
    population: 975551,
  },
  {
    slug: "oslo",
    name: "Oslo",
    country: "Norway",
    countryCode: "NO",
    lat: 59.9139,
    lon: 10.7522,
    tz: "Europe/Oslo",
    population: 693494,
  },
  {
    slug: "istanbul",
    name: "Istanbul",
    country: "Turkey",
    countryCode: "TR",
    lat: 41.0082,
    lon: 28.9784,
    tz: "Europe/Istanbul",
    population: 15462452,
  },
  {
    slug: "ankara",
    name: "Ankara",
    country: "Turkey",
    countryCode: "TR",
    lat: 39.9334,
    lon: 32.8597,
    tz: "Europe/Istanbul",
    population: 5663322,
  },
  {
    slug: "makkah",
    name: "Makkah",
    country: "Saudi Arabia",
    countryCode: "SA",
    lat: 21.3891,
    lon: 39.8579,
    tz: "Asia/Riyadh",
    population: 2042000,
  },
  {
    slug: "madinah",
    name: "Madinah",
    country: "Saudi Arabia",
    countryCode: "SA",
    lat: 24.5247,
    lon: 39.5692,
    tz: "Asia/Riyadh",
    population: 1300000,
  },
  {
    slug: "riyadh",
    name: "Riyadh",
    country: "Saudi Arabia",
    countryCode: "SA",
    lat: 24.7136,
    lon: 46.6753,
    tz: "Asia/Riyadh",
    population: 7676654,
  },
  {
    slug: "jeddah",
    name: "Jeddah",
    country: "Saudi Arabia",
    countryCode: "SA",
    lat: 21.4858,
    lon: 39.1925,
    tz: "Asia/Riyadh",
    population: 4697000,
  },
  {
    slug: "dubai",
    name: "Dubai",
    country: "United Arab Emirates",
    countryCode: "AE",
    lat: 25.2048,
    lon: 55.2708,
    tz: "Asia/Dubai",
    population: 3331000,
  },
  {
    slug: "abu-dhabi",
    name: "Abu Dhabi",
    country: "United Arab Emirates",
    countryCode: "AE",
    lat: 24.4539,
    lon: 54.3773,
    tz: "Asia/Dubai",
    population: 1483000,
  },
  {
    slug: "doha",
    name: "Doha",
    country: "Qatar",
    countryCode: "QA",
    lat: 25.2854,
    lon: 51.531,
    tz: "Asia/Qatar",
    population: 2381000,
  },
  {
    slug: "kuwait-city",
    name: "Kuwait City",
    country: "Kuwait",
    countryCode: "KW",
    lat: 29.3759,
    lon: 47.9774,
    tz: "Asia/Kuwait",
    population: 3115000,
  },
  {
    slug: "cairo",
    name: "Cairo",
    country: "Egypt",
    countryCode: "EG",
    lat: 30.0444,
    lon: 31.2357,
    tz: "Africa/Cairo",
    population: 20900604,
  },
  {
    slug: "alexandria",
    name: "Alexandria",
    country: "Egypt",
    countryCode: "EG",
    lat: 31.2001,
    lon: 29.9187,
    tz: "Africa/Cairo",
    population: 5200000,
  },
  {
    slug: "amman",
    name: "Amman",
    country: "Jordan",
    countryCode: "JO",
    lat: 31.9539,
    lon: 35.9106,
    tz: "Asia/Amman",
    population: 4061150,
  },
  {
    slug: "beirut",
    name: "Beirut",
    country: "Lebanon",
    countryCode: "LB",
    lat: 33.8938,
    lon: 35.5018,
    tz: "Asia/Beirut",
    population: 2200000,
  },
  {
    slug: "baghdad",
    name: "Baghdad",
    country: "Iraq",
    countryCode: "IQ",
    lat: 33.3152,
    lon: 44.3661,
    tz: "Asia/Baghdad",
    population: 7180889,
  },
  {
    slug: "tehran",
    name: "Tehran",
    country: "Iran",
    countryCode: "IR",
    lat: 35.6892,
    lon: 51.389,
    tz: "Asia/Tehran",
    population: 8896000,
  },
  {
    slug: "karachi",
    name: "Karachi",
    country: "Pakistan",
    countryCode: "PK",
    lat: 24.8607,
    lon: 67.0011,
    tz: "Asia/Karachi",
    population: 14910352,
  },
  {
    slug: "lahore",
    name: "Lahore",
    country: "Pakistan",
    countryCode: "PK",
    lat: 31.5204,
    lon: 74.3587,
    tz: "Asia/Karachi",
    population: 11126000,
  },
  {
    slug: "islamabad",
    name: "Islamabad",
    country: "Pakistan",
    countryCode: "PK",
    lat: 33.6844,
    lon: 73.0479,
    tz: "Asia/Karachi",
    population: 1015000,
  },
  {
    slug: "delhi",
    name: "Delhi",
    country: "India",
    countryCode: "IN",
    lat: 28.7041,
    lon: 77.1025,
    tz: "Asia/Kolkata",
    population: 32941000,
  },
  {
    slug: "mumbai",
    name: "Mumbai",
    country: "India",
    countryCode: "IN",
    lat: 19.076,
    lon: 72.8777,
    tz: "Asia/Kolkata",
    population: 20668000,
  },
  {
    slug: "hyderabad",
    name: "Hyderabad",
    country: "India",
    countryCode: "IN",
    lat: 17.385,
    lon: 78.4867,
    tz: "Asia/Kolkata",
    population: 10269000,
  },
  {
    slug: "dhaka",
    name: "Dhaka",
    country: "Bangladesh",
    countryCode: "BD",
    lat: 23.8103,
    lon: 90.4125,
    tz: "Asia/Dhaka",
    population: 22478116,
  },
  {
    slug: "kuala-lumpur",
    name: "Kuala Lumpur",
    country: "Malaysia",
    countryCode: "MY",
    lat: 3.139,
    lon: 101.6869,
    tz: "Asia/Kuala_Lumpur",
    population: 1808000,
  },
  {
    slug: "singapore",
    name: "Singapore",
    country: "Singapore",
    countryCode: "SG",
    lat: 1.3521,
    lon: 103.8198,
    tz: "Asia/Singapore",
    population: 5896686,
  },
  {
    slug: "jakarta",
    name: "Jakarta",
    country: "Indonesia",
    countryCode: "ID",
    lat: -6.2088,
    lon: 106.8456,
    tz: "Asia/Jakarta",
    population: 10770487,
  },
  {
    slug: "surabaya",
    name: "Surabaya",
    country: "Indonesia",
    countryCode: "ID",
    lat: -7.2575,
    lon: 112.7521,
    tz: "Asia/Jakarta",
    population: 2874000,
  },
  {
    slug: "bandung",
    name: "Bandung",
    country: "Indonesia",
    countryCode: "ID",
    lat: -6.9175,
    lon: 107.6191,
    tz: "Asia/Jakarta",
    population: 2444000,
  },
  {
    slug: "yogyakarta",
    name: "Yogyakarta",
    country: "Indonesia",
    countryCode: "ID",
    lat: -7.7956,
    lon: 110.3695,
    tz: "Asia/Jakarta",
    population: 422732,
  },
  {
    slug: "medan",
    name: "Medan",
    country: "Indonesia",
    countryCode: "ID",
    lat: 3.5952,
    lon: 98.6722,
    tz: "Asia/Jakarta",
    population: 2435000,
  },
  {
    slug: "sydney",
    name: "Sydney",
    country: "Australia",
    countryCode: "AU",
    lat: -33.8688,
    lon: 151.2093,
    tz: "Australia/Sydney",
    population: 5312000,
  },
  {
    slug: "melbourne",
    name: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    lat: -37.8136,
    lon: 144.9631,
    tz: "Australia/Melbourne",
    population: 5031000,
  },
  {
    slug: "casablanca",
    name: "Casablanca",
    country: "Morocco",
    countryCode: "MA",
    lat: 33.5731,
    lon: -7.5898,
    tz: "Africa/Casablanca",
    population: 3752000,
  },
  {
    slug: "algiers",
    name: "Algiers",
    country: "Algeria",
    countryCode: "DZ",
    lat: 36.7538,
    lon: 3.0588,
    tz: "Africa/Algiers",
    population: 3416000,
  },
  {
    slug: "tunis",
    name: "Tunis",
    country: "Tunisia",
    countryCode: "TN",
    lat: 36.8065,
    lon: 10.1815,
    tz: "Africa/Tunis",
    population: 1056000,
  },
  {
    slug: "lagos",
    name: "Lagos",
    country: "Nigeria",
    countryCode: "NG",
    lat: 6.5244,
    lon: 3.3792,
    tz: "Africa/Lagos",
    population: 15388000,
  },
  {
    slug: "cape-town",
    name: "Cape Town",
    country: "South Africa",
    countryCode: "ZA",
    lat: -33.9249,
    lon: 18.4241,
    tz: "Africa/Johannesburg",
    population: 4618000,
  },
];

export function getCity(slug: string): City | undefined {
  return CITIES.find((c) => c.slug === slug);
}
