// Real, sourced Islamic figures — every entry cites a classical source.
// Do NOT add entries without a Bukhari #, Muslim #, Siyar vol/page, Bidayah vol,
// or equivalent classical reference. Trust > completeness.
//
// Sources abbreviated:
//   Bukhari #     = Sahih al-Bukhari, hadith number
//   Muslim #      = Sahih Muslim, hadith number
//   Siyar         = adh-Dhahabi, Siyar A'lam an-Nubala'
//   Bidayah       = Ibn Kathir, al-Bidayah wa-n-Nihayah
//   Ibn Hisham    = Ibn Hisham, as-Sirah an-Nabawiyyah
//   Tabaqat       = Ibn Sa'd, Kitab at-Tabaqat al-Kabir

export type FigureCategory = "prophets" | "rashidun" | "sahabah" | "imams" | "hadith" | "scholars";

export type Figure = {
  slug: string;
  name: string;
  nameArabic: string;
  epithet?: string;
  category: FigureCategory;
  tag: string;
  init: string; // 1-char Arabic monogram for the card
  born?: string;
  died?: string;
  region?: string;
  body: string;
  source: string;
};

export const FIGURES: Figure[] = [
  // ============ PROPHETS ============
  {
    slug: "adam",
    name: "Ādam",
    nameArabic: "آدَم",
    epithet: "The first human, first prophet",
    category: "prophets",
    tag: "Prophet",
    init: "آ",
    body: "The first human and first prophet. Taught the names of all things (Q 2:31), fell from the Garden, and repented with the words Allāh Himself taught him (Q 7:23).",
    source: "Qur'ān 2:30–39, 7:19–25 · Bukhārī 3326",
  },
  {
    slug: "nuh",
    name: "Nūḥ",
    nameArabic: "نُوح",
    epithet: "Noah — the second Ādam",
    category: "prophets",
    tag: "Prophet",
    init: "ن",
    body: "Preached for 950 years (Q 29:14) before the Deluge. Called the 'second Ādam' because all later humans descend from his line (Q 37:77).",
    source: "Sūrat Nūḥ (71) · Q 11:25–49 · Bukhārī 3339",
  },
  {
    slug: "ibrahim",
    name: "Ibrāhīm",
    nameArabic: "إِبْرَاهِيم",
    epithet: "Abraham · Khalīl Allāh",
    category: "prophets",
    tag: "Prophet",
    init: "إ",
    body: "Khalīl Allāh — the intimate friend of God (Q 4:125). Rebuilt the Kaʿbah with his son Ismāʿīl (Q 2:127). Progenitor of the prophetic lineage.",
    source: "Q 2:124–141, 6:74–83, 37:83–113 · Bukhārī 3364",
  },
  {
    slug: "musa",
    name: "Mūsā",
    nameArabic: "مُوسَى",
    epithet: "Moses · Kalīm Allāh",
    category: "prophets",
    tag: "Prophet",
    init: "م",
    body: "Kalīm Allāh — the one to whom God spoke directly (Q 4:164). Received the Tawrāh at Mount Sinai. The Qur'ān mentions him by name more than any other prophet.",
    source: "Sūrat Ṭāhā (20), Sūrat al-Qaṣaṣ (28) · Bukhārī 3401",
  },
  {
    slug: "isa",
    name: "ʿĪsā ibn Maryam",
    nameArabic: "عِيسَى ابْنُ مَرْيَم",
    epithet: "Jesus, son of Mary",
    category: "prophets",
    tag: "Prophet",
    init: "ع",
    body: "Born of the Virgin Maryam by God's word (Q 3:47). Received the Injīl. Raised bodily to God (Q 4:158) and will return before the Day of Judgment.",
    source: "Sūrat Maryam (19), Q 3:33–63, 5:110–120 · Muslim 155",
  },
  {
    slug: "dawud",
    name: "Dāwūd",
    nameArabic: "دَاوُد",
    epithet: "David · Prophet-King",
    category: "prophets",
    tag: "Prophet",
    init: "د",
    body: "Prophet and king. Given the Zabūr (Psalms). Softened iron in his hands (Q 34:10). Father of Sulaymān.",
    source: "Q 2:251, 21:78–80, 34:10–11, 38:17–26",
  },
  {
    slug: "muhammad",
    name: "Muḥammad ﷺ",
    nameArabic: "مُحَمَّد ﷺ",
    epithet: "Khātam an-Nabiyyīn — the Seal of the Prophets",
    category: "prophets",
    tag: "Seal · ﷺ",
    init: "م",
    born: "c. 570 CE, Makkah",
    died: "11 AH / 632 CE, Madīnah",
    region: "Ḥijāz",
    body: "The final prophet. Born in the Year of the Elephant, c. 570 CE. Received revelation over 23 years. His life is the primary lens through which every earlier prophet is remembered in Islam.",
    source: "Ibn Hishām · Ibn Kathīr's Sīrah · the Ṣaḥīḥayn passim",
  },
  // ============ RĀSHIDŪN ============
  {
    slug: "abu-bakr",
    name: "Abū Bakr aṣ-Ṣiddīq",
    nameArabic: "أَبُو بَكْرٍ الصِّدِّيقُ",
    epithet: "The Truthful · First Caliph",
    category: "rashidun",
    tag: "Caliph I",
    init: "أ",
    born: "c. 573 CE, Makkah",
    died: "23 Jumādā al-Ākhirah 13 AH / 634 CE, Madīnah",
    region: "Ḥijāz",
    body: "First caliph. The Prophet's ﷺ companion in the cave of Thawr — a moment preserved in Q 9:40. Led the Riddah wars; initiated the compilation of the Qur'ān as one text.",
    source: "Bukhārī 3653–3691 · Ibn Kathīr, Bidāyah vol. 6",
  },
  {
    slug: "umar",
    name: "ʿUmar ibn al-Khaṭṭāb",
    nameArabic: "عُمَر بْن الْخَطَّاب",
    epithet: "Al-Fārūq — the Distinguisher",
    category: "rashidun",
    tag: "Caliph II",
    init: "ع",
    born: "c. 584 CE, Makkah",
    died: "23 AH / 644 CE, Madīnah",
    region: "Ḥijāz → Iraq",
    body: "Second caliph. Established the Hijri calendar, the ʿaṭāʾ registers, and much of the early administrative order.",
    source: "Bukhārī 3689 · adh-Dhahabī, Siyar · Ibn Saʿd, Ṭabaqāt",
  },
  {
    slug: "uthman",
    name: "ʿUthmān ibn ʿAffān",
    nameArabic: "عُثْمَان بْن عَفَّان",
    epithet: "Dhū an-Nūrayn — of the Two Lights",
    category: "rashidun",
    tag: "Caliph III",
    init: "ع",
    born: "c. 576 CE, Makkah",
    died: "35 AH / 656 CE, Madīnah",
    region: "Ḥijāz",
    body: "Third caliph. 'Dhū an-Nūrayn' — 'the one of two lights' — for marrying two of the Prophet's ﷺ daughters. Standardized the muṣḥaf into the ʿUthmānī rasm still used today.",
    source: "Bukhārī 3695–3706 · Ibn Kathīr, Bidāyah vol. 7",
  },
  {
    slug: "ali",
    name: "ʿAlī ibn Abī Ṭālib",
    nameArabic: "عَلِي بْن أَبِي طَالِب",
    epithet: "Bāb madīnat al-ʿilm — Gate of the City of Knowledge",
    category: "rashidun",
    tag: "Caliph IV",
    init: "ع",
    born: "c. 600 CE, Makkah",
    died: "40 AH / 661 CE, Kūfah",
    region: "Ḥijāz → Iraq",
    body: "Fourth caliph. Cousin and son-in-law of the Prophet ﷺ. The first child to embrace Islam. Renowned for eloquence, judgment, and courage.",
    source: "Bukhārī 3701 · Muslim 2404 · Nahj al-Balāghah (attrib.)",
  },
  // ============ ṢAḤĀBAH ============
  {
    slug: "aisha",
    name: "ʿĀʾishah bint Abī Bakr",
    nameArabic: "عَائِشَة بِنْت أَبِي بَكْر",
    epithet: "Umm al-Muʾminīn — Mother of the Believers",
    category: "sahabah",
    tag: "Umm al-Muʾminīn",
    init: "ع",
    body: "c. 614 – 678 CE. Wife of the Prophet ﷺ. Transmitter of 2,210 aḥādīth. Foundational voice in fiqh, tafsīr, and Sīrah.",
    source: "adh-Dhahabī, Siyar vol. 2 · Bukhārī passim",
  },
  {
    slug: "khadija",
    name: "Khadījah bint Khuwaylid",
    nameArabic: "خَدِيجَة بِنْت خُوَيْلِد",
    epithet: "The first believer",
    category: "sahabah",
    tag: "Umm al-Muʾminīn",
    init: "خ",
    body: "c. 555 – 619 CE. The Prophet's ﷺ first wife. First person to accept Islam. Merchant of Makkah.",
    source: "Bukhārī 3820, Muslim 2432 · Ibn Hishām",
  },
  {
    slug: "bilal",
    name: "Bilāl ibn Rabāḥ",
    nameArabic: "بِلَال بْن رَبَاح",
    epithet: "First muʾadhdhin of Islam",
    category: "sahabah",
    tag: "Ṣaḥābī",
    init: "ب",
    body: "c. 580 – 640 CE. Abyssinian former slave. First muʾadhdhin of Islam. Tortured under Umayyah in Makkah, freed by Abū Bakr.",
    source: "Bukhārī 3754 · Ibn Saʿd, Ṭabaqāt vol. 3",
  },
  {
    slug: "abu-hurairah",
    name: "Abū Hurayrah",
    nameArabic: "أَبُو هُرَيْرَة",
    epithet: "Most prolific transmitter of ḥadīth",
    category: "sahabah",
    tag: "Ṣaḥābī",
    init: "أ",
    body: "d. 678 CE. From the Dawsī tribe. The most prolific transmitter of prophetic ḥadīth — 5,374 narrations. Accompanied the Prophet ﷺ intensely for the last three years of his life.",
    source: "Bukhārī 3708 · adh-Dhahabī, Siyar vol. 2",
  },
  {
    slug: "fatimah",
    name: "Fāṭimah az-Zahrāʾ",
    nameArabic: "فَاطِمَة الزَّهْرَاء",
    epithet: "Mistress of the women of Paradise",
    category: "sahabah",
    tag: "Ahl al-Bayt",
    init: "ف",
    body: "c. 604 – 632 CE. Youngest daughter of the Prophet ﷺ, wife of ʿAlī, mother of Ḥasan and Ḥusayn.",
    source: "Bukhārī 3623–3624 · Muslim 2450",
  },
  {
    slug: "khalid",
    name: "Khālid ibn al-Walīd",
    nameArabic: "خَالِد بْن الْوَلِيد",
    epithet: "Sayf Allāh al-Maslūl — the Drawn Sword of God",
    category: "sahabah",
    tag: "Ṣaḥābī · Commander",
    init: "خ",
    body: "d. 642 CE. Undefeated commander through the Riddah wars and the conquests of ash-Shām and ʿIrāq.",
    source: "Bukhārī 3757 · Ṭabarī, Tārīkh",
  },
  {
    slug: "ibn-abbas",
    name: "ʿAbdullāh ibn ʿAbbās",
    nameArabic: "عَبْدُ اللَّه بْن عَبَّاس",
    epithet: "Ḥabr al-Ummah — the Scholar of the Ummah",
    category: "sahabah",
    tag: "Ṣaḥābī · Scholar",
    init: "ع",
    body: "c. 619 – 687 CE. Cousin of the Prophet ﷺ. Foundational voice in tafsīr; the Prophet ﷺ prayed for him to be taught taʾwīl.",
    source: "Bukhārī 75 (the duʿāʾ) · Ibn Kathīr's Muqaddimah",
  },
  {
    slug: "salman",
    name: "Salmān al-Fārisī",
    nameArabic: "سَلْمَان الْفَارِسِي",
    epithet: "The Persian seeker",
    category: "sahabah",
    tag: "Ṣaḥābī",
    init: "س",
    body: "d. c. 656 CE. Persian by origin. Sought the truth across Zoroastrianism, Christianity, and finally Islam. Proposed the trench at the Battle of the Khandaq.",
    source: "Bukhārī 4104 · Ṭabarānī, al-Muʿjam al-Kabīr",
  },
  // ============ IMAMS ============
  {
    slug: "abu-hanifa",
    name: "Abū Ḥanīfah an-Nuʿmān",
    nameArabic: "أَبُو حَنِيفَة النُّعْمَان",
    epithet: "Al-Imām al-Aʿẓam",
    category: "imams",
    tag: "Ḥanafī",
    init: "أ",
    born: "80 AH / 699 CE",
    died: "150 AH / 767 CE",
    region: "Kūfah",
    body: "Cloth merchant, systematic jurist. Founder of the Ḥanafī madhhab. Refused to serve as chief qāḍī and died in an Abbasid prison.",
    source: "adh-Dhahabī, Siyar vol. 6 · al-Khaṭīb, Tārīkh Baghdād",
  },
  {
    slug: "malik",
    name: "Mālik ibn Anas",
    nameArabic: "مَالِك بْن أَنَس",
    epithet: "Imām Dār al-Hijrah",
    category: "imams",
    tag: "Mālikī",
    init: "م",
    born: "93 AH / 711 CE",
    died: "179 AH / 795 CE",
    region: "Madīnah",
    body: "Compiler of al-Muwaṭṭaʾ, the earliest surviving major work of ḥadīth-fiqh. Founder of the Mālikī madhhab. Taught for 62 years.",
    source: "al-Muwaṭṭaʾ · Qāḍī ʿIyāḍ, Tartīb al-Madārik",
  },
  {
    slug: "shafii",
    name: "Muḥammad ibn Idrīs ash-Shāfiʿī",
    nameArabic: "الشَّافِعِي",
    epithet: "Nāṣir as-Sunnah — Defender of the Sunnah",
    category: "imams",
    tag: "Shāfiʿī",
    init: "ش",
    born: "150 AH / 767 CE",
    died: "204 AH / 820 CE",
    region: "Gaza → Egypt",
    body: "Founder of uṣūl al-fiqh as a formal discipline via his Risālah. Student of Mālik.",
    source: "ar-Rāzī, Manāqib ash-Shāfiʿī · Ibn Abī Ḥātim",
  },
  {
    slug: "ahmad",
    name: "Aḥmad ibn Ḥanbal",
    nameArabic: "أَحْمَد بْن حَنْبَل",
    epithet: "Imām Ahl as-Sunnah",
    category: "imams",
    tag: "Ḥanbalī",
    init: "أ",
    born: "164 AH / 780 CE",
    died: "241 AH / 855 CE",
    region: "Baghdad",
    body: "Compiled the Musnad of 30,000+ narrations. Endured the Miḥnah under three caliphs rather than affirm the createdness of the Qur'ān.",
    source: "Ibn al-Jawzī, Manāqib al-Imām Aḥmad · adh-Dhahabī, Siyar",
  },
  // ============ ḤADĪTH COMPILERS ============
  {
    slug: "bukhari",
    name: "Muḥammad al-Bukhārī",
    nameArabic: "الْبُخَارِي",
    epithet: "Amīr al-Muʾminīn fī al-Ḥadīth",
    category: "hadith",
    tag: "Ṣaḥīḥ al-Bukhārī",
    init: "ب",
    born: "194 AH / 810 CE",
    died: "256 AH / 870 CE",
    region: "Bukhārā (Uzbekistan)",
    body: "Selected 7,563 narrations from ~600,000. His Ṣaḥīḥ is the most authoritative book after the Qur'ān in Sunnī tradition.",
    source: "adh-Dhahabī, Siyar vol. 12 · Ibn Ḥajar, Hady as-Sārī",
  },
  {
    slug: "muslim",
    name: "Muslim ibn al-Ḥajjāj",
    nameArabic: "مُسْلِم بْن الْحَجَّاج",
    epithet: "Compiler of Ṣaḥīḥ Muslim",
    category: "hadith",
    tag: "Ṣaḥīḥ Muslim",
    init: "م",
    born: "c. 202 AH / 817 CE",
    died: "261 AH / 875 CE",
    region: "Nīshāpūr",
    body: "Student of Bukhārī. His Ṣaḥīḥ is arranged thematically and second only to Bukhārī's in authority.",
    source: "adh-Dhahabī, Siyar vol. 12 · an-Nawawī's Muqaddimah",
  },
  {
    slug: "abu-dawud",
    name: "Abū Dāwūd as-Sijistānī",
    nameArabic: "أَبُو دَاوُد",
    epithet: "Compiler of Sunan Abī Dāwūd",
    category: "hadith",
    tag: "Sunan",
    init: "أ",
    born: "202 AH / 817 CE",
    died: "275 AH / 889 CE",
    region: "Baṣrah",
    body: "Focused his Sunan on legal ḥadīth. One of the 'Kutub as-Sittah.'",
    source: "adh-Dhahabī, Siyar vol. 13",
  },
  {
    slug: "tirmidhi",
    name: "Muḥammad at-Tirmidhī",
    nameArabic: "التِّرْمِذِي",
    epithet: "Compiler of al-Jāmiʿ",
    category: "hadith",
    tag: "Jāmiʿ",
    init: "ت",
    born: "c. 209 AH / 824 CE",
    died: "279 AH / 892 CE",
    region: "Termez (Uzbekistan)",
    body: "His Jāmiʿ grades each ḥadīth (ṣaḥīḥ, ḥasan, ḍaʿīf) — a first in the genre.",
    source: "adh-Dhahabī, Siyar vol. 13",
  },
  {
    slug: "nasai",
    name: "Aḥmad an-Nasāʾī",
    nameArabic: "النَّسَائِي",
    epithet: "Compiler of Sunan an-Nasāʾī",
    category: "hadith",
    tag: "Sunan",
    init: "ن",
    born: "c. 215 AH / 830 CE",
    died: "303 AH / 915 CE",
    region: "Nasā (Khurāsān)",
    body: "His Sunan al-Kubrā and its abridgement al-Mujtabā are among the strictest of the Six Books.",
    source: "adh-Dhahabī, Siyar vol. 14",
  },
  // ============ SCHOLARS ============
  {
    slug: "ghazali",
    name: "Abū Ḥāmid al-Ghazālī",
    nameArabic: "الْغَزَالِي",
    epithet: "Ḥujjat al-Islām",
    category: "scholars",
    tag: "Ḥujjat al-Islām",
    init: "غ",
    born: "450 AH / 1058 CE",
    died: "505 AH / 1111 CE",
    region: "Ṭūs → Baghdad → Damascus",
    body: "Author of Iḥyāʾ ʿUlūm ad-Dīn. Bridged fiqh, kalām, and taṣawwuf.",
    source: "as-Subkī, Ṭabaqāt ash-Shāfiʿiyyah vol. 6",
  },
  {
    slug: "ibn-taymiyyah",
    name: "Ibn Taymiyyah",
    nameArabic: "ابْن تَيْمِيَّة",
    epithet: "Shaykh al-Islām",
    category: "scholars",
    tag: "Shaykh al-Islām",
    init: "ت",
    born: "661 AH / 1263 CE",
    died: "728 AH / 1328 CE",
    region: "Ḥarrān → Damascus",
    body: "Reformer and prolific writer. His Majmūʿ al-Fatāwā spans 37 volumes. Died in the Damascus citadel.",
    source: "Ibn Kathīr, Bidāyah vol. 14",
  },
  {
    slug: "ibn-kathir",
    name: "Ibn Kathīr",
    nameArabic: "ابْن كَثِير",
    epithet: "Mufassir · Historian",
    category: "scholars",
    tag: "Mufassir",
    init: "ك",
    born: "c. 700 AH / 1300 CE",
    died: "774 AH / 1373 CE",
    region: "Boṣrā → Damascus",
    body: "Student of Ibn Taymiyyah. Author of the widely read Tafsīr al-Qurʾān al-ʿAẓīm and al-Bidāyah wa-n-Nihāyah.",
    source: "Ibn Ḥajar, ad-Durar al-Kāminah",
  },
  {
    slug: "nawawi",
    name: "Yaḥyā an-Nawawī",
    nameArabic: "النَّوَوِي",
    epithet: "Muḥyī ad-Dīn",
    category: "scholars",
    tag: "Muḥaddith · Faqīh",
    init: "ن",
    born: "631 AH / 1233 CE",
    died: "676 AH / 1277 CE",
    region: "Nawā (Syria) → Damascus",
    body: "Author of al-Arbaʿīn (the Forty Ḥadīth), Riyāḍ aṣ-Ṣāliḥīn, and the commentary on Ṣaḥīḥ Muslim. Died at 44.",
    source: "as-Sakhāwī, at-Tarjamah · adh-Dhahabī",
  },
];

export const CATEGORY_META: Record<FigureCategory, { label: string; short: string }> = {
  prophets: { label: "Prophets (peace be upon them)", short: "Prophets" },
  rashidun: { label: "The Rāshidūn Caliphs", short: "The Rāshidūn" },
  sahabah: { label: "Selected Ṣaḥābah", short: "Ṣaḥābah" },
  imams: { label: "Imams of the Four Sunnī Schools", short: "Imams of Fiqh" },
  hadith: { label: "The Ḥadīth Compilers", short: "Ḥadīth masters" },
  scholars: { label: "Later scholars", short: "Later scholars" },
};

export function getAllFigures(): ReadonlyArray<Figure> {
  return FIGURES;
}

export function getFigureBySlug(slug: string): Figure | undefined {
  return FIGURES.find((f) => f.slug === slug);
}

export function getFiguresByCategory(cat: FigureCategory): Figure[] {
  return FIGURES.filter((f) => f.category === cat);
}
